version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      # vue 3 gives error `Cannot read properties of undefined (reading 'component')`
      - dependency-name: vue
        versions: [ ">=3.0.0" ]
      # eslint 9 gives error `Unknown options: extensions`
      - dependency-name: eslint
        versions: [ ">=9.0.0" ]
      # [eslint] Cannot read config file: .../zigbee2mqtt-networkmap/node_modules/@vue/eslint-config-standard/index.js
      - dependency-name: "@vue/eslint-config-standard"
        versions: [ ">=9.0.0" ]
      # [eslint] Failed to load plugin 'vue' declared in '.eslintrc.js': Cannot find module 'vue-eslint-parser'
      - dependency-name: eslint-plugin-vue
        versions: [ ">=10.0.0" ]
    groups:
      major:
        update-types:
          - major
      minor:
        update-types:
          - minor
          - patch
